/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CandidatoRouteRouteImport } from './routes/candidato/route'
import { Route as NaoAutenticadoRouteRouteImport } from './routes/_naoAutenticado/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CandidatorotasIndexRouteImport } from './routes/candidato/(rotas)/index'
import { Route as CandidatorotasVagasRouteImport } from './routes/candidato/(rotas)/vagas'
import { Route as CandidatorotasEditarRouteImport } from './routes/candidato/(rotas)/editar'
import { Route as CandidatorotasCandidaturasRouteImport } from './routes/candidato/(rotas)/candidaturas'
import { Route as NaoAutenticadorotasLoginRouteImport } from './routes/_naoAutenticado/(rotas)/login'
import { Route as NaoAutenticadorotasEsqueciMinhaSenhaRouteImport } from './routes/_naoAutenticado/(rotas)/esqueci-minha-senha'
import { Route as NaoAutenticadorotasCadastroRouteImport } from './routes/_naoAutenticado/(rotas)/cadastro'

const CandidatoRouteRoute = CandidatoRouteRouteImport.update({
  id: '/candidato',
  path: '/candidato',
  getParentRoute: () => rootRouteImport,
} as any)
const NaoAutenticadoRouteRoute = NaoAutenticadoRouteRouteImport.update({
  id: '/_naoAutenticado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatorotasIndexRoute = CandidatorotasIndexRouteImport.update({
  id: '/(rotas)/',
  path: '/',
  getParentRoute: () => CandidatoRouteRoute,
} as any)
const CandidatorotasVagasRoute = CandidatorotasVagasRouteImport.update({
  id: '/(rotas)/vagas',
  path: '/vagas',
  getParentRoute: () => CandidatoRouteRoute,
} as any)
const CandidatorotasEditarRoute = CandidatorotasEditarRouteImport.update({
  id: '/(rotas)/editar',
  path: '/editar',
  getParentRoute: () => CandidatoRouteRoute,
} as any)
const CandidatorotasCandidaturasRoute =
  CandidatorotasCandidaturasRouteImport.update({
    id: '/(rotas)/candidaturas',
    path: '/candidaturas',
    getParentRoute: () => CandidatoRouteRoute,
  } as any)
const NaoAutenticadorotasLoginRoute =
  NaoAutenticadorotasLoginRouteImport.update({
    id: '/(rotas)/login',
    path: '/login',
    getParentRoute: () => NaoAutenticadoRouteRoute,
  } as any)
const NaoAutenticadorotasEsqueciMinhaSenhaRoute =
  NaoAutenticadorotasEsqueciMinhaSenhaRouteImport.update({
    id: '/(rotas)/esqueci-minha-senha',
    path: '/esqueci-minha-senha',
    getParentRoute: () => NaoAutenticadoRouteRoute,
  } as any)
const NaoAutenticadorotasCadastroRoute =
  NaoAutenticadorotasCadastroRouteImport.update({
    id: '/(rotas)/cadastro',
    path: '/cadastro',
    getParentRoute: () => NaoAutenticadoRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidato': typeof CandidatoRouteRouteWithChildren
  '/cadastro': typeof NaoAutenticadorotasCadastroRoute
  '/esqueci-minha-senha': typeof NaoAutenticadorotasEsqueciMinhaSenhaRoute
  '/login': typeof NaoAutenticadorotasLoginRoute
  '/candidato/candidaturas': typeof CandidatorotasCandidaturasRoute
  '/candidato/editar': typeof CandidatorotasEditarRoute
  '/candidato/vagas': typeof CandidatorotasVagasRoute
  '/candidato/': typeof CandidatorotasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof NaoAutenticadorotasCadastroRoute
  '/esqueci-minha-senha': typeof NaoAutenticadorotasEsqueciMinhaSenhaRoute
  '/login': typeof NaoAutenticadorotasLoginRoute
  '/candidato/candidaturas': typeof CandidatorotasCandidaturasRoute
  '/candidato/editar': typeof CandidatorotasEditarRoute
  '/candidato/vagas': typeof CandidatorotasVagasRoute
  '/candidato': typeof CandidatorotasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_naoAutenticado': typeof NaoAutenticadoRouteRouteWithChildren
  '/candidato': typeof CandidatoRouteRouteWithChildren
  '/_naoAutenticado/(rotas)/cadastro': typeof NaoAutenticadorotasCadastroRoute
  '/_naoAutenticado/(rotas)/esqueci-minha-senha': typeof NaoAutenticadorotasEsqueciMinhaSenhaRoute
  '/_naoAutenticado/(rotas)/login': typeof NaoAutenticadorotasLoginRoute
  '/candidato/(rotas)/candidaturas': typeof CandidatorotasCandidaturasRoute
  '/candidato/(rotas)/editar': typeof CandidatorotasEditarRoute
  '/candidato/(rotas)/vagas': typeof CandidatorotasVagasRoute
  '/candidato/(rotas)/': typeof CandidatorotasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/candidato'
    | '/cadastro'
    | '/esqueci-minha-senha'
    | '/login'
    | '/candidato/candidaturas'
    | '/candidato/editar'
    | '/candidato/vagas'
    | '/candidato/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/esqueci-minha-senha'
    | '/login'
    | '/candidato/candidaturas'
    | '/candidato/editar'
    | '/candidato/vagas'
    | '/candidato'
  id:
    | '__root__'
    | '/'
    | '/_naoAutenticado'
    | '/candidato'
    | '/_naoAutenticado/(rotas)/cadastro'
    | '/_naoAutenticado/(rotas)/esqueci-minha-senha'
    | '/_naoAutenticado/(rotas)/login'
    | '/candidato/(rotas)/candidaturas'
    | '/candidato/(rotas)/editar'
    | '/candidato/(rotas)/vagas'
    | '/candidato/(rotas)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NaoAutenticadoRouteRoute: typeof NaoAutenticadoRouteRouteWithChildren
  CandidatoRouteRoute: typeof CandidatoRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/candidato': {
      id: '/candidato'
      path: '/candidato'
      fullPath: '/candidato'
      preLoaderRoute: typeof CandidatoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_naoAutenticado': {
      id: '/_naoAutenticado'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof NaoAutenticadoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidato/(rotas)/': {
      id: '/candidato/(rotas)/'
      path: '/'
      fullPath: '/candidato/'
      preLoaderRoute: typeof CandidatorotasIndexRouteImport
      parentRoute: typeof CandidatoRouteRoute
    }
    '/candidato/(rotas)/vagas': {
      id: '/candidato/(rotas)/vagas'
      path: '/vagas'
      fullPath: '/candidato/vagas'
      preLoaderRoute: typeof CandidatorotasVagasRouteImport
      parentRoute: typeof CandidatoRouteRoute
    }
    '/candidato/(rotas)/editar': {
      id: '/candidato/(rotas)/editar'
      path: '/editar'
      fullPath: '/candidato/editar'
      preLoaderRoute: typeof CandidatorotasEditarRouteImport
      parentRoute: typeof CandidatoRouteRoute
    }
    '/candidato/(rotas)/candidaturas': {
      id: '/candidato/(rotas)/candidaturas'
      path: '/candidaturas'
      fullPath: '/candidato/candidaturas'
      preLoaderRoute: typeof CandidatorotasCandidaturasRouteImport
      parentRoute: typeof CandidatoRouteRoute
    }
    '/_naoAutenticado/(rotas)/login': {
      id: '/_naoAutenticado/(rotas)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof NaoAutenticadorotasLoginRouteImport
      parentRoute: typeof NaoAutenticadoRouteRoute
    }
    '/_naoAutenticado/(rotas)/esqueci-minha-senha': {
      id: '/_naoAutenticado/(rotas)/esqueci-minha-senha'
      path: '/esqueci-minha-senha'
      fullPath: '/esqueci-minha-senha'
      preLoaderRoute: typeof NaoAutenticadorotasEsqueciMinhaSenhaRouteImport
      parentRoute: typeof NaoAutenticadoRouteRoute
    }
    '/_naoAutenticado/(rotas)/cadastro': {
      id: '/_naoAutenticado/(rotas)/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof NaoAutenticadorotasCadastroRouteImport
      parentRoute: typeof NaoAutenticadoRouteRoute
    }
  }
}

interface NaoAutenticadoRouteRouteChildren {
  NaoAutenticadorotasCadastroRoute: typeof NaoAutenticadorotasCadastroRoute
  NaoAutenticadorotasEsqueciMinhaSenhaRoute: typeof NaoAutenticadorotasEsqueciMinhaSenhaRoute
  NaoAutenticadorotasLoginRoute: typeof NaoAutenticadorotasLoginRoute
}

const NaoAutenticadoRouteRouteChildren: NaoAutenticadoRouteRouteChildren = {
  NaoAutenticadorotasCadastroRoute: NaoAutenticadorotasCadastroRoute,
  NaoAutenticadorotasEsqueciMinhaSenhaRoute:
    NaoAutenticadorotasEsqueciMinhaSenhaRoute,
  NaoAutenticadorotasLoginRoute: NaoAutenticadorotasLoginRoute,
}

const NaoAutenticadoRouteRouteWithChildren =
  NaoAutenticadoRouteRoute._addFileChildren(NaoAutenticadoRouteRouteChildren)

interface CandidatoRouteRouteChildren {
  CandidatorotasCandidaturasRoute: typeof CandidatorotasCandidaturasRoute
  CandidatorotasEditarRoute: typeof CandidatorotasEditarRoute
  CandidatorotasVagasRoute: typeof CandidatorotasVagasRoute
  CandidatorotasIndexRoute: typeof CandidatorotasIndexRoute
}

const CandidatoRouteRouteChildren: CandidatoRouteRouteChildren = {
  CandidatorotasCandidaturasRoute: CandidatorotasCandidaturasRoute,
  CandidatorotasEditarRoute: CandidatorotasEditarRoute,
  CandidatorotasVagasRoute: CandidatorotasVagasRoute,
  CandidatorotasIndexRoute: CandidatorotasIndexRoute,
}

const CandidatoRouteRouteWithChildren = CandidatoRouteRoute._addFileChildren(
  CandidatoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NaoAutenticadoRouteRoute: NaoAutenticadoRouteRouteWithChildren,
  CandidatoRouteRoute: CandidatoRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
