/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidacaoEmailRouteImport } from './routes/validacao-email'
import { Route as NaoAutenticadoRouteRouteImport } from './routes/_naoAutenticado/route'
import { Route as AutenticadoRouteRouteImport } from './routes/_autenticado/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutenticadoNotificacoesRouteImport } from './routes/_autenticado/notificacoes'
import { Route as AutenticadoEmpresaRouteRouteImport } from './routes/_autenticado/empresa/route'
import { Route as AutenticadoCandidatoRouteRouteImport } from './routes/_autenticado/candidato/route'
import { Route as NaoAutenticadorotasLoginRouteImport } from './routes/_naoAutenticado/(rotas)/login'
import { Route as NaoAutenticadorotasEsqueciMinhaSenhaRouteImport } from './routes/_naoAutenticado/(rotas)/esqueci-minha-senha'
import { Route as NaoAutenticadorotasCadastroRouteImport } from './routes/_naoAutenticado/(rotas)/cadastro'
import { Route as AutenticadoEmpresarotasIndexRouteImport } from './routes/_autenticado/empresa/(rotas)/index'
import { Route as AutenticadoCandidatorotasIndexRouteImport } from './routes/_autenticado/candidato/(rotas)/index'
import { Route as AutenticadoEmpresarotasEditarRouteImport } from './routes/_autenticado/empresa/(rotas)/editar'
import { Route as AutenticadoCandidatorotasEditarRouteImport } from './routes/_autenticado/candidato/(rotas)/editar'
import { Route as AutenticadoCandidatorotasCandidaturasRouteImport } from './routes/_autenticado/candidato/(rotas)/candidaturas'
import { Route as AutenticadoEmpresarotasVagaIndexRouteImport } from './routes/_autenticado/empresa/(rotas)/vaga/index'
import { Route as AutenticadoCandidatorotasVagaIndexRouteImport } from './routes/_autenticado/candidato/(rotas)/vaga/index'
import { Route as AutenticadoCandidatorotasVagaIdRouteImport } from './routes/_autenticado/candidato/(rotas)/vaga/$id'
import { Route as AutenticadoCandidatorotasEmpresaIdEmpresaRouteImport } from './routes/_autenticado/candidato/(rotas)/empresa/$idEmpresa'
import { Route as AutenticadoEmpresarotasVagaIdIndexRouteImport } from './routes/_autenticado/empresa/(rotas)/vaga/$id/index'
import { Route as AutenticadoEmpresarotasVagaIdCandidatoIdAplicacaoRouteImport } from './routes/_autenticado/empresa/(rotas)/vaga/$id/candidato/$idAplicacao'

const ValidacaoEmailRoute = ValidacaoEmailRouteImport.update({
  id: '/validacao-email',
  path: '/validacao-email',
  getParentRoute: () => rootRouteImport,
} as any)
const NaoAutenticadoRouteRoute = NaoAutenticadoRouteRouteImport.update({
  id: '/_naoAutenticado',
  getParentRoute: () => rootRouteImport,
} as any)
const AutenticadoRouteRoute = AutenticadoRouteRouteImport.update({
  id: '/_autenticado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutenticadoNotificacoesRoute = AutenticadoNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AutenticadoRouteRoute,
} as any)
const AutenticadoEmpresaRouteRoute = AutenticadoEmpresaRouteRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AutenticadoRouteRoute,
} as any)
const AutenticadoCandidatoRouteRoute =
  AutenticadoCandidatoRouteRouteImport.update({
    id: '/candidato',
    path: '/candidato',
    getParentRoute: () => AutenticadoRouteRoute,
  } as any)
const NaoAutenticadorotasLoginRoute =
  NaoAutenticadorotasLoginRouteImport.update({
    id: '/(rotas)/login',
    path: '/login',
    getParentRoute: () => NaoAutenticadoRouteRoute,
  } as any)
const NaoAutenticadorotasEsqueciMinhaSenhaRoute =
  NaoAutenticadorotasEsqueciMinhaSenhaRouteImport.update({
    id: '/(rotas)/esqueci-minha-senha',
    path: '/esqueci-minha-senha',
    getParentRoute: () => NaoAutenticadoRouteRoute,
  } as any)
const NaoAutenticadorotasCadastroRoute =
  NaoAutenticadorotasCadastroRouteImport.update({
    id: '/(rotas)/cadastro',
    path: '/cadastro',
    getParentRoute: () => NaoAutenticadoRouteRoute,
  } as any)
const AutenticadoEmpresarotasIndexRoute =
  AutenticadoEmpresarotasIndexRouteImport.update({
    id: '/(rotas)/',
    path: '/',
    getParentRoute: () => AutenticadoEmpresaRouteRoute,
  } as any)
const AutenticadoCandidatorotasIndexRoute =
  AutenticadoCandidatorotasIndexRouteImport.update({
    id: '/(rotas)/',
    path: '/',
    getParentRoute: () => AutenticadoCandidatoRouteRoute,
  } as any)
const AutenticadoEmpresarotasEditarRoute =
  AutenticadoEmpresarotasEditarRouteImport.update({
    id: '/(rotas)/editar',
    path: '/editar',
    getParentRoute: () => AutenticadoEmpresaRouteRoute,
  } as any)
const AutenticadoCandidatorotasEditarRoute =
  AutenticadoCandidatorotasEditarRouteImport.update({
    id: '/(rotas)/editar',
    path: '/editar',
    getParentRoute: () => AutenticadoCandidatoRouteRoute,
  } as any)
const AutenticadoCandidatorotasCandidaturasRoute =
  AutenticadoCandidatorotasCandidaturasRouteImport.update({
    id: '/(rotas)/candidaturas',
    path: '/candidaturas',
    getParentRoute: () => AutenticadoCandidatoRouteRoute,
  } as any)
const AutenticadoEmpresarotasVagaIndexRoute =
  AutenticadoEmpresarotasVagaIndexRouteImport.update({
    id: '/(rotas)/vaga/',
    path: '/vaga/',
    getParentRoute: () => AutenticadoEmpresaRouteRoute,
  } as any)
const AutenticadoCandidatorotasVagaIndexRoute =
  AutenticadoCandidatorotasVagaIndexRouteImport.update({
    id: '/(rotas)/vaga/',
    path: '/vaga/',
    getParentRoute: () => AutenticadoCandidatoRouteRoute,
  } as any)
const AutenticadoCandidatorotasVagaIdRoute =
  AutenticadoCandidatorotasVagaIdRouteImport.update({
    id: '/(rotas)/vaga/$id',
    path: '/vaga/$id',
    getParentRoute: () => AutenticadoCandidatoRouteRoute,
  } as any)
const AutenticadoCandidatorotasEmpresaIdEmpresaRoute =
  AutenticadoCandidatorotasEmpresaIdEmpresaRouteImport.update({
    id: '/(rotas)/empresa/$idEmpresa',
    path: '/empresa/$idEmpresa',
    getParentRoute: () => AutenticadoCandidatoRouteRoute,
  } as any)
const AutenticadoEmpresarotasVagaIdIndexRoute =
  AutenticadoEmpresarotasVagaIdIndexRouteImport.update({
    id: '/(rotas)/vaga/$id/',
    path: '/vaga/$id/',
    getParentRoute: () => AutenticadoEmpresaRouteRoute,
  } as any)
const AutenticadoEmpresarotasVagaIdCandidatoIdAplicacaoRoute =
  AutenticadoEmpresarotasVagaIdCandidatoIdAplicacaoRouteImport.update({
    id: '/(rotas)/vaga/$id/candidato/$idAplicacao',
    path: '/vaga/$id/candidato/$idAplicacao',
    getParentRoute: () => AutenticadoEmpresaRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/validacao-email': typeof ValidacaoEmailRoute
  '/candidato': typeof AutenticadoCandidatoRouteRouteWithChildren
  '/empresa': typeof AutenticadoEmpresaRouteRouteWithChildren
  '/notificacoes': typeof AutenticadoNotificacoesRoute
  '/cadastro': typeof NaoAutenticadorotasCadastroRoute
  '/esqueci-minha-senha': typeof NaoAutenticadorotasEsqueciMinhaSenhaRoute
  '/login': typeof NaoAutenticadorotasLoginRoute
  '/candidato/candidaturas': typeof AutenticadoCandidatorotasCandidaturasRoute
  '/candidato/editar': typeof AutenticadoCandidatorotasEditarRoute
  '/empresa/editar': typeof AutenticadoEmpresarotasEditarRoute
  '/candidato/': typeof AutenticadoCandidatorotasIndexRoute
  '/empresa/': typeof AutenticadoEmpresarotasIndexRoute
  '/candidato/empresa/$idEmpresa': typeof AutenticadoCandidatorotasEmpresaIdEmpresaRoute
  '/candidato/vaga/$id': typeof AutenticadoCandidatorotasVagaIdRoute
  '/candidato/vaga/': typeof AutenticadoCandidatorotasVagaIndexRoute
  '/empresa/vaga/': typeof AutenticadoEmpresarotasVagaIndexRoute
  '/empresa/vaga/$id/': typeof AutenticadoEmpresarotasVagaIdIndexRoute
  '/empresa/vaga/$id/candidato/$idAplicacao': typeof AutenticadoEmpresarotasVagaIdCandidatoIdAplicacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/validacao-email': typeof ValidacaoEmailRoute
  '/notificacoes': typeof AutenticadoNotificacoesRoute
  '/cadastro': typeof NaoAutenticadorotasCadastroRoute
  '/esqueci-minha-senha': typeof NaoAutenticadorotasEsqueciMinhaSenhaRoute
  '/login': typeof NaoAutenticadorotasLoginRoute
  '/candidato/candidaturas': typeof AutenticadoCandidatorotasCandidaturasRoute
  '/candidato/editar': typeof AutenticadoCandidatorotasEditarRoute
  '/empresa/editar': typeof AutenticadoEmpresarotasEditarRoute
  '/candidato': typeof AutenticadoCandidatorotasIndexRoute
  '/empresa': typeof AutenticadoEmpresarotasIndexRoute
  '/candidato/empresa/$idEmpresa': typeof AutenticadoCandidatorotasEmpresaIdEmpresaRoute
  '/candidato/vaga/$id': typeof AutenticadoCandidatorotasVagaIdRoute
  '/candidato/vaga': typeof AutenticadoCandidatorotasVagaIndexRoute
  '/empresa/vaga': typeof AutenticadoEmpresarotasVagaIndexRoute
  '/empresa/vaga/$id': typeof AutenticadoEmpresarotasVagaIdIndexRoute
  '/empresa/vaga/$id/candidato/$idAplicacao': typeof AutenticadoEmpresarotasVagaIdCandidatoIdAplicacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_autenticado': typeof AutenticadoRouteRouteWithChildren
  '/_naoAutenticado': typeof NaoAutenticadoRouteRouteWithChildren
  '/validacao-email': typeof ValidacaoEmailRoute
  '/_autenticado/candidato': typeof AutenticadoCandidatoRouteRouteWithChildren
  '/_autenticado/empresa': typeof AutenticadoEmpresaRouteRouteWithChildren
  '/_autenticado/notificacoes': typeof AutenticadoNotificacoesRoute
  '/_naoAutenticado/(rotas)/cadastro': typeof NaoAutenticadorotasCadastroRoute
  '/_naoAutenticado/(rotas)/esqueci-minha-senha': typeof NaoAutenticadorotasEsqueciMinhaSenhaRoute
  '/_naoAutenticado/(rotas)/login': typeof NaoAutenticadorotasLoginRoute
  '/_autenticado/candidato/(rotas)/candidaturas': typeof AutenticadoCandidatorotasCandidaturasRoute
  '/_autenticado/candidato/(rotas)/editar': typeof AutenticadoCandidatorotasEditarRoute
  '/_autenticado/empresa/(rotas)/editar': typeof AutenticadoEmpresarotasEditarRoute
  '/_autenticado/candidato/(rotas)/': typeof AutenticadoCandidatorotasIndexRoute
  '/_autenticado/empresa/(rotas)/': typeof AutenticadoEmpresarotasIndexRoute
  '/_autenticado/candidato/(rotas)/empresa/$idEmpresa': typeof AutenticadoCandidatorotasEmpresaIdEmpresaRoute
  '/_autenticado/candidato/(rotas)/vaga/$id': typeof AutenticadoCandidatorotasVagaIdRoute
  '/_autenticado/candidato/(rotas)/vaga/': typeof AutenticadoCandidatorotasVagaIndexRoute
  '/_autenticado/empresa/(rotas)/vaga/': typeof AutenticadoEmpresarotasVagaIndexRoute
  '/_autenticado/empresa/(rotas)/vaga/$id/': typeof AutenticadoEmpresarotasVagaIdIndexRoute
  '/_autenticado/empresa/(rotas)/vaga/$id/candidato/$idAplicacao': typeof AutenticadoEmpresarotasVagaIdCandidatoIdAplicacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/validacao-email'
    | '/candidato'
    | '/empresa'
    | '/notificacoes'
    | '/cadastro'
    | '/esqueci-minha-senha'
    | '/login'
    | '/candidato/candidaturas'
    | '/candidato/editar'
    | '/empresa/editar'
    | '/candidato/'
    | '/empresa/'
    | '/candidato/empresa/$idEmpresa'
    | '/candidato/vaga/$id'
    | '/candidato/vaga/'
    | '/empresa/vaga/'
    | '/empresa/vaga/$id/'
    | '/empresa/vaga/$id/candidato/$idAplicacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/validacao-email'
    | '/notificacoes'
    | '/cadastro'
    | '/esqueci-minha-senha'
    | '/login'
    | '/candidato/candidaturas'
    | '/candidato/editar'
    | '/empresa/editar'
    | '/candidato'
    | '/empresa'
    | '/candidato/empresa/$idEmpresa'
    | '/candidato/vaga/$id'
    | '/candidato/vaga'
    | '/empresa/vaga'
    | '/empresa/vaga/$id'
    | '/empresa/vaga/$id/candidato/$idAplicacao'
  id:
    | '__root__'
    | '/'
    | '/_autenticado'
    | '/_naoAutenticado'
    | '/validacao-email'
    | '/_autenticado/candidato'
    | '/_autenticado/empresa'
    | '/_autenticado/notificacoes'
    | '/_naoAutenticado/(rotas)/cadastro'
    | '/_naoAutenticado/(rotas)/esqueci-minha-senha'
    | '/_naoAutenticado/(rotas)/login'
    | '/_autenticado/candidato/(rotas)/candidaturas'
    | '/_autenticado/candidato/(rotas)/editar'
    | '/_autenticado/empresa/(rotas)/editar'
    | '/_autenticado/candidato/(rotas)/'
    | '/_autenticado/empresa/(rotas)/'
    | '/_autenticado/candidato/(rotas)/empresa/$idEmpresa'
    | '/_autenticado/candidato/(rotas)/vaga/$id'
    | '/_autenticado/candidato/(rotas)/vaga/'
    | '/_autenticado/empresa/(rotas)/vaga/'
    | '/_autenticado/empresa/(rotas)/vaga/$id/'
    | '/_autenticado/empresa/(rotas)/vaga/$id/candidato/$idAplicacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutenticadoRouteRoute: typeof AutenticadoRouteRouteWithChildren
  NaoAutenticadoRouteRoute: typeof NaoAutenticadoRouteRouteWithChildren
  ValidacaoEmailRoute: typeof ValidacaoEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validacao-email': {
      id: '/validacao-email'
      path: '/validacao-email'
      fullPath: '/validacao-email'
      preLoaderRoute: typeof ValidacaoEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_naoAutenticado': {
      id: '/_naoAutenticado'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof NaoAutenticadoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_autenticado': {
      id: '/_autenticado'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AutenticadoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_autenticado/notificacoes': {
      id: '/_autenticado/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AutenticadoNotificacoesRouteImport
      parentRoute: typeof AutenticadoRouteRoute
    }
    '/_autenticado/empresa': {
      id: '/_autenticado/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof AutenticadoEmpresaRouteRouteImport
      parentRoute: typeof AutenticadoRouteRoute
    }
    '/_autenticado/candidato': {
      id: '/_autenticado/candidato'
      path: '/candidato'
      fullPath: '/candidato'
      preLoaderRoute: typeof AutenticadoCandidatoRouteRouteImport
      parentRoute: typeof AutenticadoRouteRoute
    }
    '/_naoAutenticado/(rotas)/login': {
      id: '/_naoAutenticado/(rotas)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof NaoAutenticadorotasLoginRouteImport
      parentRoute: typeof NaoAutenticadoRouteRoute
    }
    '/_naoAutenticado/(rotas)/esqueci-minha-senha': {
      id: '/_naoAutenticado/(rotas)/esqueci-minha-senha'
      path: '/esqueci-minha-senha'
      fullPath: '/esqueci-minha-senha'
      preLoaderRoute: typeof NaoAutenticadorotasEsqueciMinhaSenhaRouteImport
      parentRoute: typeof NaoAutenticadoRouteRoute
    }
    '/_naoAutenticado/(rotas)/cadastro': {
      id: '/_naoAutenticado/(rotas)/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof NaoAutenticadorotasCadastroRouteImport
      parentRoute: typeof NaoAutenticadoRouteRoute
    }
    '/_autenticado/empresa/(rotas)/': {
      id: '/_autenticado/empresa/(rotas)/'
      path: '/'
      fullPath: '/empresa/'
      preLoaderRoute: typeof AutenticadoEmpresarotasIndexRouteImport
      parentRoute: typeof AutenticadoEmpresaRouteRoute
    }
    '/_autenticado/candidato/(rotas)/': {
      id: '/_autenticado/candidato/(rotas)/'
      path: '/'
      fullPath: '/candidato/'
      preLoaderRoute: typeof AutenticadoCandidatorotasIndexRouteImport
      parentRoute: typeof AutenticadoCandidatoRouteRoute
    }
    '/_autenticado/empresa/(rotas)/editar': {
      id: '/_autenticado/empresa/(rotas)/editar'
      path: '/editar'
      fullPath: '/empresa/editar'
      preLoaderRoute: typeof AutenticadoEmpresarotasEditarRouteImport
      parentRoute: typeof AutenticadoEmpresaRouteRoute
    }
    '/_autenticado/candidato/(rotas)/editar': {
      id: '/_autenticado/candidato/(rotas)/editar'
      path: '/editar'
      fullPath: '/candidato/editar'
      preLoaderRoute: typeof AutenticadoCandidatorotasEditarRouteImport
      parentRoute: typeof AutenticadoCandidatoRouteRoute
    }
    '/_autenticado/candidato/(rotas)/candidaturas': {
      id: '/_autenticado/candidato/(rotas)/candidaturas'
      path: '/candidaturas'
      fullPath: '/candidato/candidaturas'
      preLoaderRoute: typeof AutenticadoCandidatorotasCandidaturasRouteImport
      parentRoute: typeof AutenticadoCandidatoRouteRoute
    }
    '/_autenticado/empresa/(rotas)/vaga/': {
      id: '/_autenticado/empresa/(rotas)/vaga/'
      path: '/vaga'
      fullPath: '/empresa/vaga/'
      preLoaderRoute: typeof AutenticadoEmpresarotasVagaIndexRouteImport
      parentRoute: typeof AutenticadoEmpresaRouteRoute
    }
    '/_autenticado/candidato/(rotas)/vaga/': {
      id: '/_autenticado/candidato/(rotas)/vaga/'
      path: '/vaga'
      fullPath: '/candidato/vaga/'
      preLoaderRoute: typeof AutenticadoCandidatorotasVagaIndexRouteImport
      parentRoute: typeof AutenticadoCandidatoRouteRoute
    }
    '/_autenticado/candidato/(rotas)/vaga/$id': {
      id: '/_autenticado/candidato/(rotas)/vaga/$id'
      path: '/vaga/$id'
      fullPath: '/candidato/vaga/$id'
      preLoaderRoute: typeof AutenticadoCandidatorotasVagaIdRouteImport
      parentRoute: typeof AutenticadoCandidatoRouteRoute
    }
    '/_autenticado/candidato/(rotas)/empresa/$idEmpresa': {
      id: '/_autenticado/candidato/(rotas)/empresa/$idEmpresa'
      path: '/empresa/$idEmpresa'
      fullPath: '/candidato/empresa/$idEmpresa'
      preLoaderRoute: typeof AutenticadoCandidatorotasEmpresaIdEmpresaRouteImport
      parentRoute: typeof AutenticadoCandidatoRouteRoute
    }
    '/_autenticado/empresa/(rotas)/vaga/$id/': {
      id: '/_autenticado/empresa/(rotas)/vaga/$id/'
      path: '/vaga/$id'
      fullPath: '/empresa/vaga/$id/'
      preLoaderRoute: typeof AutenticadoEmpresarotasVagaIdIndexRouteImport
      parentRoute: typeof AutenticadoEmpresaRouteRoute
    }
    '/_autenticado/empresa/(rotas)/vaga/$id/candidato/$idAplicacao': {
      id: '/_autenticado/empresa/(rotas)/vaga/$id/candidato/$idAplicacao'
      path: '/vaga/$id/candidato/$idAplicacao'
      fullPath: '/empresa/vaga/$id/candidato/$idAplicacao'
      preLoaderRoute: typeof AutenticadoEmpresarotasVagaIdCandidatoIdAplicacaoRouteImport
      parentRoute: typeof AutenticadoEmpresaRouteRoute
    }
  }
}

interface AutenticadoCandidatoRouteRouteChildren {
  AutenticadoCandidatorotasCandidaturasRoute: typeof AutenticadoCandidatorotasCandidaturasRoute
  AutenticadoCandidatorotasEditarRoute: typeof AutenticadoCandidatorotasEditarRoute
  AutenticadoCandidatorotasIndexRoute: typeof AutenticadoCandidatorotasIndexRoute
  AutenticadoCandidatorotasEmpresaIdEmpresaRoute: typeof AutenticadoCandidatorotasEmpresaIdEmpresaRoute
  AutenticadoCandidatorotasVagaIdRoute: typeof AutenticadoCandidatorotasVagaIdRoute
  AutenticadoCandidatorotasVagaIndexRoute: typeof AutenticadoCandidatorotasVagaIndexRoute
}

const AutenticadoCandidatoRouteRouteChildren: AutenticadoCandidatoRouteRouteChildren =
  {
    AutenticadoCandidatorotasCandidaturasRoute:
      AutenticadoCandidatorotasCandidaturasRoute,
    AutenticadoCandidatorotasEditarRoute: AutenticadoCandidatorotasEditarRoute,
    AutenticadoCandidatorotasIndexRoute: AutenticadoCandidatorotasIndexRoute,
    AutenticadoCandidatorotasEmpresaIdEmpresaRoute:
      AutenticadoCandidatorotasEmpresaIdEmpresaRoute,
    AutenticadoCandidatorotasVagaIdRoute: AutenticadoCandidatorotasVagaIdRoute,
    AutenticadoCandidatorotasVagaIndexRoute:
      AutenticadoCandidatorotasVagaIndexRoute,
  }

const AutenticadoCandidatoRouteRouteWithChildren =
  AutenticadoCandidatoRouteRoute._addFileChildren(
    AutenticadoCandidatoRouteRouteChildren,
  )

interface AutenticadoEmpresaRouteRouteChildren {
  AutenticadoEmpresarotasEditarRoute: typeof AutenticadoEmpresarotasEditarRoute
  AutenticadoEmpresarotasIndexRoute: typeof AutenticadoEmpresarotasIndexRoute
  AutenticadoEmpresarotasVagaIndexRoute: typeof AutenticadoEmpresarotasVagaIndexRoute
  AutenticadoEmpresarotasVagaIdIndexRoute: typeof AutenticadoEmpresarotasVagaIdIndexRoute
  AutenticadoEmpresarotasVagaIdCandidatoIdAplicacaoRoute: typeof AutenticadoEmpresarotasVagaIdCandidatoIdAplicacaoRoute
}

const AutenticadoEmpresaRouteRouteChildren: AutenticadoEmpresaRouteRouteChildren =
  {
    AutenticadoEmpresarotasEditarRoute: AutenticadoEmpresarotasEditarRoute,
    AutenticadoEmpresarotasIndexRoute: AutenticadoEmpresarotasIndexRoute,
    AutenticadoEmpresarotasVagaIndexRoute:
      AutenticadoEmpresarotasVagaIndexRoute,
    AutenticadoEmpresarotasVagaIdIndexRoute:
      AutenticadoEmpresarotasVagaIdIndexRoute,
    AutenticadoEmpresarotasVagaIdCandidatoIdAplicacaoRoute:
      AutenticadoEmpresarotasVagaIdCandidatoIdAplicacaoRoute,
  }

const AutenticadoEmpresaRouteRouteWithChildren =
  AutenticadoEmpresaRouteRoute._addFileChildren(
    AutenticadoEmpresaRouteRouteChildren,
  )

interface AutenticadoRouteRouteChildren {
  AutenticadoCandidatoRouteRoute: typeof AutenticadoCandidatoRouteRouteWithChildren
  AutenticadoEmpresaRouteRoute: typeof AutenticadoEmpresaRouteRouteWithChildren
  AutenticadoNotificacoesRoute: typeof AutenticadoNotificacoesRoute
}

const AutenticadoRouteRouteChildren: AutenticadoRouteRouteChildren = {
  AutenticadoCandidatoRouteRoute: AutenticadoCandidatoRouteRouteWithChildren,
  AutenticadoEmpresaRouteRoute: AutenticadoEmpresaRouteRouteWithChildren,
  AutenticadoNotificacoesRoute: AutenticadoNotificacoesRoute,
}

const AutenticadoRouteRouteWithChildren =
  AutenticadoRouteRoute._addFileChildren(AutenticadoRouteRouteChildren)

interface NaoAutenticadoRouteRouteChildren {
  NaoAutenticadorotasCadastroRoute: typeof NaoAutenticadorotasCadastroRoute
  NaoAutenticadorotasEsqueciMinhaSenhaRoute: typeof NaoAutenticadorotasEsqueciMinhaSenhaRoute
  NaoAutenticadorotasLoginRoute: typeof NaoAutenticadorotasLoginRoute
}

const NaoAutenticadoRouteRouteChildren: NaoAutenticadoRouteRouteChildren = {
  NaoAutenticadorotasCadastroRoute: NaoAutenticadorotasCadastroRoute,
  NaoAutenticadorotasEsqueciMinhaSenhaRoute:
    NaoAutenticadorotasEsqueciMinhaSenhaRoute,
  NaoAutenticadorotasLoginRoute: NaoAutenticadorotasLoginRoute,
}

const NaoAutenticadoRouteRouteWithChildren =
  NaoAutenticadoRouteRoute._addFileChildren(NaoAutenticadoRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutenticadoRouteRoute: AutenticadoRouteRouteWithChildren,
  NaoAutenticadoRouteRoute: NaoAutenticadoRouteRouteWithChildren,
  ValidacaoEmailRoute: ValidacaoEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
